# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\Repozytoria\MinHash

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\Repozytoria\MinHash

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Repozytoria\MinHash\CMakeFiles D:\Repozytoria\MinHash\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Repozytoria\MinHash\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named app

# Build rule for target.
app: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 app
.PHONY : app

# fast build rule for target.
app/fast:
	$(MAKE) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/build
.PHONY : app/fast

src/extensiondetector.obj: src/extensiondetector.cpp.obj

.PHONY : src/extensiondetector.obj

# target to build an object file
src/extensiondetector.cpp.obj:
	$(MAKE) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/src/extensiondetector.cpp.obj
.PHONY : src/extensiondetector.cpp.obj

src/extensiondetector.i: src/extensiondetector.cpp.i

.PHONY : src/extensiondetector.i

# target to preprocess a source file
src/extensiondetector.cpp.i:
	$(MAKE) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/src/extensiondetector.cpp.i
.PHONY : src/extensiondetector.cpp.i

src/extensiondetector.s: src/extensiondetector.cpp.s

.PHONY : src/extensiondetector.s

# target to generate assembly for a file
src/extensiondetector.cpp.s:
	$(MAKE) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/src/extensiondetector.cpp.s
.PHONY : src/extensiondetector.cpp.s

src/filemanager.obj: src/filemanager.cpp.obj

.PHONY : src/filemanager.obj

# target to build an object file
src/filemanager.cpp.obj:
	$(MAKE) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/src/filemanager.cpp.obj
.PHONY : src/filemanager.cpp.obj

src/filemanager.i: src/filemanager.cpp.i

.PHONY : src/filemanager.i

# target to preprocess a source file
src/filemanager.cpp.i:
	$(MAKE) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/src/filemanager.cpp.i
.PHONY : src/filemanager.cpp.i

src/filemanager.s: src/filemanager.cpp.s

.PHONY : src/filemanager.s

# target to generate assembly for a file
src/filemanager.cpp.s:
	$(MAKE) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/src/filemanager.cpp.s
.PHONY : src/filemanager.cpp.s

src/main.obj: src/main.cpp.obj

.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/osdetector.obj: src/osdetector.cpp.obj

.PHONY : src/osdetector.obj

# target to build an object file
src/osdetector.cpp.obj:
	$(MAKE) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/src/osdetector.cpp.obj
.PHONY : src/osdetector.cpp.obj

src/osdetector.i: src/osdetector.cpp.i

.PHONY : src/osdetector.i

# target to preprocess a source file
src/osdetector.cpp.i:
	$(MAKE) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/src/osdetector.cpp.i
.PHONY : src/osdetector.cpp.i

src/osdetector.s: src/osdetector.cpp.s

.PHONY : src/osdetector.s

# target to generate assembly for a file
src/osdetector.cpp.s:
	$(MAKE) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/src/osdetector.cpp.s
.PHONY : src/osdetector.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... app
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... src/extensiondetector.obj
	@echo ... src/extensiondetector.i
	@echo ... src/extensiondetector.s
	@echo ... src/filemanager.obj
	@echo ... src/filemanager.i
	@echo ... src/filemanager.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/osdetector.obj
	@echo ... src/osdetector.i
	@echo ... src/osdetector.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

