#ifndef ARRAYGENERATOR_H_
#define ARRAYGENERATOR_H_
#include <iostream>
#include <random>
#include <ctime>

/**
 * ArrayGenerator generates uint64_t arrays.
 **/
class ArrayGenerator
{
public:
    // Default constructor of ArrayGenerator.
    ArrayGenerator();

    // Generates empty uint64_t array of given length and returns it.
    uint64_t * generateUint64Array(int);

    // Generates uint64_t array of given length and returns it
    // filled with numbers generated by the random numbers generator 
    uint64_t * generateRandomUint64Array(int);

private:
    // Generates single random uint64_t number.
    uint64_t generateRandomUint64();

    unsigned int seed;
    std::mt19937_64 engine;
    std::uniform_int_distribution<uint64_t> distribution;
};

#endif